export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_USER_ERROR = 'SIGN_UP_USER_ERROR';
export const LOG_IN_USER = 'LOG_IN_USER';
export const LOG_IN_USER_ERROR = 'LOG_IN_USER_ERROR';
export const FETCH_ALL_ACCOUNTS = 'FETCH_ALL_ACCOUNTS';
export const FETCH_ALL_ACCOUNTS_ERROR = 'FETCH_ALL_ACCOUNTS_ERROR';
export const FETCH_USER_ACCOUNT_DETAILS = 'FETCH_USER_ACCOUNT_DETAILS';
export const FETCH_USER_ACCOUNT_DETAILS_START = 'FETCH_USER_ACCOUNT_DETAILS_START';